### ISSUE TITLE
CloseGuard error after EOFException

### ISSUE THREAD

**Issue by wonderfly** [google/google-http-java-client#116]
_From [yan...@google.com](https://code.google.com/u/111815493751521097215/) on May 19, 2012 07:09:00_

Version of google-http-java-client (e.g. 1.5.0-beta)? 1.9.0-beta Java environment (e.g. Java 6, Android 2.3, App Engine)? Android Describe the problem. Reported by aalbert:

When this exception is thrown:
05-18 16:18:10.546   895  1825 E App: java.io.EOFException
05-18 16:18:10.546   895  1825 E App:   at libcore.io.Streams.readAsciiLine(Streams.java:203)
05-18 16:18:10.546   895  1825 E App:   at libcore.net.http.HttpEngine.readResponseHeaders(HttpEngine.java:582)
05-18 16:18:10.546   895  1825 E App:   at libcore.net.http.HttpEngine.readResponse(HttpEngine.java:836)
05-18 16:18:10.546   895  1825 E App:   at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:274)
05-18 16:18:10.546   895  1825 E App:   at libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:486)
05-18 16:18:10.546   895  1825 E App:   at libcore.net.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:134)
05-18 16:18:10.546   895  1825 E App:   at com.google.api.client.http.javanet.NetHttpResponse.<init>(NetHttpResponse.java:37)
05-18 16:18:10.546   895  1825 E App:   at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:89)
05-18 16:18:10.546   895  1825 E App:   at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:814)
05-18 16:18:10.546   895  1825 E App:   at com.google.api.client.googleapis.json.GoogleJsonResponseException.execute(GoogleJsonResponseException.java:182)
05-18 16:18:10.546   895  1825 E App:   at com.google.api.client.googleapis.services.GoogleClient.executeUnparsed(GoogleClient.java:115)
05-18 16:18:10.546   895  1825 E App:   at com.google.api.client.http.json.JsonHttpRequest.executeUnparsed(JsonHttpRequest.java:112)

The underlying connection is not closed properly and we get a CloseGuard error:

05-18 16:19:10.343   895   904 E StrictMode:    at dalvik.system.CloseGuard.open(CloseGuard.java:184)
05-18 16:19:10.343   895   904 E StrictMode:    at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:287)
05-18 16:19:10.343   895   904 E StrictMode:    at libcore.net.http.HttpConnection.setupSecureSocket(HttpConnection.java:210)
05-18 16:19:10.343   895   904 E StrictMode:    at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:478)
05-18 16:19:10.343   895   904 E StrictMode:    at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:433)
05-18 16:19:10.343   895   904 E StrictMode:    at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:293)
05-18 16:19:10.343   895   904 E StrictMode:    at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:243)
05-18 16:19:10.343   895   904 E StrictMode:    at libcore.net.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:80)
05-18 16:19:10.343   895   904 E StrictMode:    at libcore.net.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:165)
05-18 16:19:10.343   895   904 E StrictMode:    at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:88) How would you expect it to be fixed? No CloseGuard error.

_Original issue: http://code.google.com/p/google-http-java-client/issues/detail?id=116_

**Comment by Kester4android** [comment]
if (Build.VERSION.SDK != null
&& Build.VERSION.SDK_INT > 13) {
urlConnect.setRequestProperty("Connection", "close");
}
