### ISSUE TITLE
Cookie parsing across all android versions

### ISSUE THREAD

**Issue by wonderfly** [google/google-http-java-client#196]
_From [yincrash](https://code.google.com/u/yincrash/) on February 06, 2013 07:59:15_

External references, such as a standards document, or specification? http://developer.android.com/reference/java/net/HttpCookie.html#parse(java.lang.String) http://developer.android.com/reference/org/apache/http/impl/cookie/package-summary.html Java environments (e.g. Java 6, Android 2.3, App Engine, or All)? Android all Please describe the feature requested. It would be nice to have a cookie parser in the client. Android 2.2 and below do not have java.net.HttpCookie, and the apache implementation is very overly complex (like the rest of HttpClient) and to do generic cookie parsing with it would require conversion in to HttpParams while HttpCookie can just parse strings.

_Original issue: http://code.google.com/p/google-http-java-client/issues/detail?id=196_

**Comment by mattwhisenhunt** [comment]
Thank you for your feature request. This client library is currently in maintenance mode. We are fixing necessary bugs and adding essential features to ensure this library continues to meet your needs for accessing Google APIs. After careful consideration, we have decided not to proceed with this enhancement. If you disagree, please feel free to re-open this issue and explain why you believe it is essential for users of this client library.
