### ISSUE TITLE
HttpResponseException  doesn't have getResponse method

### ISSUE THREAD

**Issue by wonderfly** [google/google-http-java-client#204]
_From [me@sunchangming.com](https://code.google.com/u/me@sunchangming.com/) on March 08, 2013 20:53:37_

Referenced documentation: https://code.google.com/p/google-http-java-client/wiki/HTTP Please describe in detail the wiki documentation request: The following code in wiki documentation cannot be compiled.

try {
    request.execute()
  } catch (HttpResponseException e) {
    System.err.println(e.getResponse().parseAsString());
  }

_Original issue: http://code.google.com/p/google-http-java-client/issues/detail?id=204_

**Comment by ejona86** [comment]
The wiki no longer exists. Closing.
