### ISSUE TITLE
PUT + Empty Body tries to send content

### ISSUE THREAD

**Issue by wonderfly** [google/google-http-java-client#220]
_From [chris.mark.jenkins@gmail.com](https://code.google.com/u/chris.mark.jenkins@gmail.com/) on May 03, 2013 11:25:11_

Version of google-http-java-client (e.g. 1.5.0-beta)? 1.14.1 beta Java environment (e.g. Java 6, Android 2.3, App Engine)? Android 4.2.X (Nexus 4/7) Describe the problem. When trying to send a PUT request to express with an empty body (passing null for HttpContent) it appears that the request does not EOL so will never finish sending data.

I have only tested this with against a node running express 3 end point. How would you expect it to be fixed? The request should perform like the generated curl command.

So this code does not work:
HttpRequest request = getHttpRequestFactory()
                .buildPutRequest(new GenericUrl(getURL()), null);

The cURL request this generates does work. Which suggests that this is not a server issue but more the client handling Null content incorrectly.

This is the generated cURL:
curl -v --compressed -X PUT -H 'Accept: application/json' -H 'Accept-Encoding: gzip' -H 'Content-Type: application/json' -H 'Cookie: sid=dfdsfdsfdfsddsfdsfdsf' -H 'connection: close' -- http://my.domain.com/some/path/dfdfddfdf To work around this I had to force an empty object into the content:
final HttpContent content = new JsonHttpContent(getJsonFactory(), new Object());
HttpRequest request = getHttpRequestFactory()
                .buildPutRequest(new GenericUrl(getURL()), content);

_Original issue: http://code.google.com/p/google-http-java-client/issues/detail?id=220_

**Comment by JustinBeckwith** [comment]
There's a dup around here somewhere
