### ISSUE TITLE
DataStore may support the version and expired

### ISSUE THREAD

**Issue by wonderfly** [google/google-http-java-client#239]
_From [ayonggu1...@gmail.com](https://code.google.com/u/113363869639450650984/) on August 06, 2013 23:59:59_

May the datastore should support version or expired or other mechanism to give up the datastore by factory.getDataStore(key).

Data may change and use new.

thanks.

_Original issue: http://code.google.com/p/google-http-java-client/issues/detail?id=239_

**Comment by JustinBeckwith** [comment]
Please use the datastore package in https://github.com/GoogleCloudPlatform/google-cloud-java/
