### ISSUE TITLE
Support for Apache http client v4.3

### ISSUE THREAD

**Issue by wonderfly** [google/google-http-java-client#250]
_From [jerome.l...@gmail.com](https://code.google.com/u/117799849441628740609/) on October 10, 2013 03:02:27_

External references, such as a standards document, or specification? Java environments (e.g. Java 6, Android 2.3, App Engine, or All)? mostly java 6 Please describe the feature requested. Please add supports for Apach http clients v4.3
currently, ApacheHttpTransport uses plenty of deprecated methods that make connection fails, noticeably when using an http proxy, throwing :
java.lang.IllegalStateException: Socket factory must implement SchemeLayeredSocketFactory

_Original issue: http://code.google.com/p/google-http-java-client/issues/detail?id=250_

**Comment by i386** [comment]
This also causes incompatibilities in the OAuth Client https://github.com/google/google-api-java-client/issues/928

**Comment by dadoonet** [comment]
+1

**Comment by kaviarasugovindarajusc** [comment]
+1

**Comment by joeyvmason** [comment]
+1

**Comment by matthiaso** [comment]
+1

**Comment by pkohout-profitsee** [comment]
+1
any news about this issue?

**Comment by chingor13** [comment]
google-(api|http|oauth)-java-client are all using newer versions of httpclient (4.5.3 in 1.24.1 and 4.5.5 in 1.25.0)
