### ISSUE TITLE
HttpResponse parseAs returns all null elements

### ISSUE THREAD

**Issue by bmaxfie** [google/google-http-java-client#319]
HttpResponse parseAs() returns DirectionsResult with null routes and geocodedWaypoints arrays when parseAsString() shows response has valid data contained within json that shows a valid request was made.

See StackOverflow post:

http://stackoverflow.com/questions/35307088/directionresult-has-null-routes-and-waypoints-google-directions-api

**Comment by kusan-thana** [comment]
Got same problem...

I can only deserialize using Gson manually on the String

**Comment by bmaxfie** [comment]
kusan-thana. Check out my StackOverflow post answer. Despite the intuition that I should not have been getting a response with points without an API key, including it made HttpResponse be able to parse the Json as expected. 

It is possible that the Json points in the requests without the API key were just garbage values and thus the parser made the object null. Either way, following my answer in my post seemed to fix the problem. You can post on StackOverflow if you have any more questions.

**Comment by samgurtman** [comment]
The real issue as far as I can tell is not using the @Key annotation on each field of your POJO
