### ISSUE TITLE
Key/Value Pair parser support for Really Simple Syndication (RSS)?

### ISSUE THREAD

**Issue by wonderfly** [google/google-http-java-client#32]
_From [Zaid.Dag...@gmail.com](https://code.google.com/u/117917434572281178926/) on September 10, 2011 02:33:55_

External references, such as a standards document, or specification? http://en.wikipedia.org/wiki/RSS Java environments (e.g. Java 6, Android 2.3, App Engine, or All)? Any Please describe the feature requested. Would it be possible to extend the key/value pairing parser to support RSS? RSS holds a very closely related structure to Atom. The only variation is the lack of a default namespace.

_Original issue: http://code.google.com/p/google-http-java-client/issues/detail?id=32_

**Comment by mattwhisenhunt** [comment]
Thank you for your feature request. This client library is currently in maintenance mode. We are fixing necessary bugs and adding essential features to ensure this library continues to meet your needs for accessing Google APIs. After careful consideration, we have decided not to proceed with this enhancement. If you disagree, please feel free to re-open this issue and explain why you believe it is essential for users of this client library.
