### ISSUE TITLE
Json serialization should be left to existing libraries

### ISSUE THREAD

**Issue by doom777** [google/google-http-java-client#326]
What's the point of having your own code to serialize and deserialize Json? Don't you guys think that it's better delegated out to teams which have loads of experience in this not-so-simple field, while you can focus on actual http work. Wouldn't it be better to let those libraries deal with ser/deser work, being how mature they are and how many edge cases they came up with and solved already.

They are also much more feature rich. For example take the Key annotation. It's very primitive, compare to the slew of Annotations that Jackson and Gson provide. `@JsonView` `@JsonIgnore`, `@MixedIn`, `@JsonSerializer`. Right now, I am writing this issue because I need custom Serialization on my special spatial types, and I can't do it, having to resolve to reading into String, and then passing the String to the Gson, instead of simply providing HttpRequestFactory with a good deserializer, and letting it do the work.

I understand the need to have wrappers, so you can plug in any serializer there is, but they should be very thing, and just delegate the whole work. For example, GsonFactory should have two constructors
`GsonFactory(){
  this(new Gson());
}
`
and `GsonFactory(Gson gson){
   this.gson = gson;
}`

I think this change can still be made even with backwards compatibility to how it's done now. I know it's a large project, but in the end, you will have less code (less opportunity for bugs), and more optimal. As the Civilization quote says: "A designer knows that he has achieved perfection not when there is nothing to add, but when there is nothing left to take away"

**Comment by MarianoTucat** [comment]
@doom777 I agree with you. Still you can easily implement your own:

- `ObjectParser` to parse your responses and make it use the deserializer you want (I'm using Jackson and it is straightforward), 
- `AbstractHttpContent` and make it use the serializer you want (same here for Jackson).

**Comment by mattwhisenhunt** [comment]
It looks like a member of our great community answered your questions. Thanks Community! Please feel free to reopen if you have any more questions.
