### ISSUE TITLE
Add OSGI metadata to the JAR

### ISSUE THREAD

**Issue by elharo** [google/google-http-java-client#328]
The Cloud Tools for Eclipse team https://github.com/GoogleCloudPlatform/gcloud-eclipse-tools would like to add OSGI metadata to the final jar file. This will enable us to pull in this dependency from Maven Central rather than copying the binary file into our source tree. This will also assist any other developer who wants to reference this library from an Eclipse plug-in or another OSGI application.

This should have minimal impact on anyone not using OSGI. That is, it's just some extra entries in MANIFEST.MF everyone else will ignore. E.g.

Bundle-ManifestVersion: 2
Bundle-SymbolicName: com.google.http-java-client
Bundle-Version: 1.2.3
Export-Package: com.google.http-java-client;version="1.2.3"

(That's just an example, not an actual working patch.)
See http://blog.osgi.org/2013/01/get-help-adding-osgi-metadata-to-your.html

If you're amenable to this, I'll send a real patch.

**Comment by elharo** [comment]
Ping. Can I send a patch for this?

**Comment by garrettjonesgoogle** [comment]
Sure, send a PR. We already accepted a similar PR in google-oauth-java-client: https://github.com/google/google-oauth-java-client/commit/57fd88b34bea69005c0a3bf0ad547a7a3acb2005 .

**Comment by elharo** [comment]
Thanks. I'll work on this. I don't seem able to assign the bug to me though.

**Comment by mattwhisenhunt** [comment]
Fixed by #345
