### ISSUE TITLE
Incorrect versioning in the central maven repository for com.google.http-client:google-http-client

### ISSUE THREAD

**Issue by tim-vbn** [google/google-http-java-client#330]
The maven-metadata.xml file has incorrect versioning information as seen below:

```
<metadata>
<groupId>com.google.http-client</groupId>
<artifactId>google-http-client</artifactId>
<versioning>
<latest>1.5.3-beta</latest>
<release>1.5.3-beta</release>
<versions>
<version>1.5.0-beta</version>
<version>1.5.3-beta</version>
</versions>
<lastUpdated>20111021163718</lastUpdated>
</versioning>
</metadata>
```

This results in the error

`[ERROR] Failed to execute goal on project: Could not resolve dependencies for project: Failed to collect dependencies at com.google.appengine.tools:appengine-gcs-client:jar:RELEASE -> com.google.http-client:google-http-client:jar:[1.19.0,2.0): No versions available for com.google.http-client:google-http-client:jar:[1.19.0,2.0) within specified range`

I must edit the metadata in my local repository in order to get my build to succeed.

**Comment by aleemstreak** [comment]
@tim-vbn how are you editing your local repo?

**Comment by arrix** [comment]
Here is a temporary workout around using `<exclusion>` to exclude the transitive dependency.

```
    <dependency>
        <groupId>com.google.appengine.tools</groupId>
        <artifactId>appengine-gcs-client</artifactId>
        <version>0.6</version>
        <exclusions>
            <exclusion>
                <!-- TODO remove me after the issue is fixed https://github.com/google/google-http-java-client/issues/330 -->
                <groupId>com.google.http-client</groupId>
                <artifactId>google-http-client</artifactId>
            </exclusion>
        </exclusions> 
    </dependency>

    <!-- Add the transitive dependency explicity  -->
    <dependency>
        <groupId>com.google.http-client</groupId>
        <artifactId>google-http-client</artifactId>
        <version>1.22.0</version>
    </dependency>
```
http://stackoverflow.com/questions/38537416/maven-build-error-in-jenkins-semi-time-sensitive/38537760

**Comment by mattwhisenhunt** [comment]
I think this has been cleared up in subsequent releases. Is anyone still experiencing this bug?
