### ISSUE TITLE
GenericUrl corrupts query parameters by not handling values in a generic fashion

### ISSUE THREAD

**Issue by prgp** [google/google-http-java-client#331]
`GenericUrl` assumes that all query parameters are UTF-8 strings, even though `set` and `put` take objects it pretends that they are just a `String`, this means something like `.set("value", new byte[] { 0x12 })` produces gibberish.

If you create a `GenericUrl`(which you must to be able to use `HttpRequestFactory.buildGetRequest` or similar) then it corrupts valid non-UTF-8 encoded query parameters rather than leaving as is:
 
```
new GenericUrl("http://some.url/path?binaryQueryParameter=%EE")
```

changes the URL to become:

```
http://some.url/path?binaryQueryParameter=%EF%BF%BD
```

which is clearly does not have the same meaning.

There seems to be several sensible ways of solving this problem:
* support encoding of 'binary' data - percent/url encoding is an encoding of binary data, not text
* support setting a `Charset` for encoding text query parameter values
* support another (maybe via an interface or annotation) mechanism to convert a query parameter value into either 'binary' or 'text' (the latter would then use the set `Charset` to convert into 'binary' for percent/url encoding)

Of course technically if this was really a generic URL object then it should not be handling "query parameters" which is a specific interpretation of the "query" part of a HTTP URL.  Maybe it would be better to make `GenericUrl` extensible and allow the "query" handling to be replaced by implementations ...

**Comment by ejona86** [comment]
The Object argument is to allow passing in collections in addition to Strings. Yes, everything is converted to a String and then encoded as UTF-8. Using non-ASCII in URLs is already pretty shaky, but general binary can't be supported. If you need binary, encode your byte[] as Base64 and then provide the string to GenericUrl.

I do understand that the query string can be opaque, but it is &-delimeted key=value pairs for this library. URLs are very complicated and there is very low need to support all its capabilities here.
