### ISSUE TITLE
User attribute “phones” cannot be set to empty

### ISSUE THREAD

**Issue by martin-lizner** [google/google-http-java-client#335]
Im invoking Google API using the google-api-services-admin-directory directory_v1-rev71-1.22.0 java library. Having integration with [Identity Management](https://github.com/Evolveum/connector-googleapps) solution Im able to add or remove values from user attribute "phones" via executing Directory.Users.Patch.

Unfortunately Im unable to delete the phones value completely. [API Documentation](https://developers.google.com/resources/api-libraries/documentation/admin/directory_v1/java/latest/com/google/api/services/admin/directory/model/User.html#setPhones%28java.lang.Object%29) suggests using the null value as input in setPhones(java.lang.Object phones), but that did not help me - change is just not propagated. I also tried some other input types... e.g. empty ArrayList() and so on but to no good.

It seems to me there might be bug in the Google API since situations when phones attribute is not touched or nulled are both referred as null value.

Thanks for help,

Martin Lizner

**Comment by mattwhisenhunt** [comment]
It may be an API bug. Would you mind trying to reproduce it in [API Explorer](https://developers.google.com/apis-explorer/#p/)

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
