### ISSUE TITLE
NetHttpRequest should only set Content-Length if unset

### ISSUE THREAD

**Issue by monktastic** [google/google-http-java-client#346]
https://github.com/google/google-http-java-client/blob/75c2b202b8de32810fba77e1e5a7c71d274ae5e9/google-http-client/src/main/java/com/google/api/client/http/javanet/NetHttpRequest.java#L65

If the user sets Content-Length (and sun.net.http.allowRestrictedHeaders=true) then this will duplicate the header (which servers may reject: https://tools.ietf.org/html/rfc7230#section-3.3.2).

HttpURLConnection uses that flag to determine whether addRequestProperty can add restricted headers like "Content-Length"

**Comment by mattwhisenhunt** [comment]
Fixed by #347
