### ISSUE TITLE
Update Guava to 20.0.0

### ISSUE THREAD

**Issue by elharo** [google/google-http-java-client#348]
21 requires Java 8, so stick with 20

**Comment by garrettjonesgoogle** [comment]
@ejona86 , I haven't looked over the surface of this repo yet - what is the rule for exposing Guava from `google-http-java-client`? 

If Guava is exposed to consumers, the 17.0 -> 20.0 upgrade will be somewhat disruptive; they are more than 2 years apart, meaning that code against the earlier version may break when the runtime is the later version.

**Comment by ejona86** [comment]
20 broke a lot of gRPC users, and due to some Precondition overloads added to 20 users can't force a lower version. [gRPC decided to downgrade to 19](https://github.com/grpc/grpc-java/pull/2751) for the moment to allow time for the libraries to catch up.

I'd suggest updating to 19 here as well.

**Comment by mattwhisenhunt** [comment]
Fixed in #380.

**Comment by garrettjonesgoogle** [comment]
For those checking after the fact, we settled with Guava 19.0.
