### ISSUE TITLE
Unplug Gson

### ISSUE THREAD

**Issue by danyma** [google/google-http-java-client#354]
Hello

I am using both google-http-client and google-gson. In my case I need the response to be just a normal text. When using both libs, gson get plugged to google-http-client and by result my response is formatted as a json.

My question is how i can get response as a normal text and also use gson library with google-http-client without getting it plugged.

**Comment by mattwhisenhunt** [comment]
The response formats available vary from API to API so you need to check the documentation of the library/API you are trying to use and see if it supports plain text.

As your question about Gson, I'm not really sure what you mean about getting plugged other than the custom exclusion strategies. But I can tell you Gson is working with JSON and has no plain text capabilities.
