### ISSUE TITLE
com.google.api.client.json.webtoken.Payload toString() does not work when audience is not a String

### ISSUE THREAD

**Issue by mnwebb** [google/google-http-java-client#358]
If audience is set as an array of Strings, the toString() method does not put correctly

This is the output of toString() I get 

payload {aud=[Ljava.lang.String;@30b6af72, exp=14572217, iss=issuer, sub=subject, nonce=nonce}

**Comment by mattwhisenhunt** [comment]
@mnwebb, would you be willing to submit a PR that would resolve this?

**Comment by chingor13** [comment]
I am unable to reproduce this. A simple test case that passes:

```java
public class JsonWebTokenTest extends TestCase  {
  public void testToString() {
    JsonWebToken.Payload payload = new Payload();
    List<String> audience = new ArrayList<String>();
    audience.add("foo");
    audience.add("bar");
    payload.setAudience(audience);
    assertEquals("{aud=[foo, bar]}", payload.toString());
  }
}
```

If you can provide a simple reproduction case, then we can address the issue.
