### ISSUE TITLE
Does this library have an ECCN?

### ISSUE THREAD

**Issue by otramony** [google/google-http-java-client#381]
Hello. Our team would like to use/include your library in our product, and since we export outside of the U.S., we're required to provide ECCN (Export Control Classification Number) information for all 3rd-party libraries that may use/include encryption. 

We're asking because of code used in:
google-http-client\src\main\java\com\google\api\client\json\webtoken\JsonWebSignature.java
google-http-client\src\main\java\com\google\api\client\util\SecurityUtils.java

**Comment by mattwhisenhunt** [comment]
My very very unofficial suggestion would be to have your engineers and lawyers get together and classify this open source library with the number you feel is most accurate.

This project is in maintenance mode and we just don't have access to the resources required to come up with those classifications.
