### ISSUE TITLE
Question: GzipCompressingEntity equivalent?

### ISSUE THREAD

**Issue by theangrydev** [google/google-http-java-client#389]
What (if any) is the equivalent `HttpContent` implementation that behaves in the same way as `org.apache.http.client.entity.GzipCompressingEntity` in this library?

**Comment by mattwhisenhunt** [comment]
I'm not sure if com.google.api.client.http.GZipEncoding is what you are looking for. This project needs some compression attention, there are some open tickets I am hoping to address early next month.

**Comment by theangrydev** [comment]
Thanks, that seems to be what I was looking for.
