### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by buchgr** [google/google-http-java-client#390]
Hi,

are there any plans on making a release anytime soon? We need a relatively new version of apache http client and would really like this [1] fix. We are currently using our own patched version :(.

cc: @ejona86 😄 

[1] https://github.com/google/google-http-java-client/commit/a31c6d827ae9c4438c1b1997bcd794967c7544f4

**Comment by briantq** [comment]
I would also be interested in hearing the timeline for the next release. It appears Apache Http Client has been upgraded but there hasn't been a release.  It would be great to get the security fixes released so applications can use Google Cloud without exposing themselves to security vulnerabilities (as a number of GC SDKs depend on this library).

**Comment by alexvanboxel** [comment]
The following commit fixes a crash in Apache Beam (that dependents on this lib), where a BigQuery Table Row with Null values (so a release is appreciates, so we can upgrade the dependency):

https://github.com/google/google-http-java-client/commit/d2d73b11aaacdf791cd7a411ea1e1936ae09bb16#diff-055e9f3229f09cd87a28d54fbd02afda

**Comment by JustinBeckwith** [comment]
Greetings folks!  And apologies for the delay here.  We're working on getting some infrastructure changes in place that should make releases much easier.  We will keep this thread updated as we get closer to a release!

**Comment by jadekler** [comment]
1.24.1 has been released.
