### ISSUE TITLE
java.lang.IllegalStateException: unknown code for readObject at 0x3c (<)

### ISSUE THREAD

**Issue by pengcao** [google/google-http-java-client#396]
java.lang.IllegalStateException: unknown code for readObject at 0x3c (<)

**Comment by mattwhisenhunt** [comment]
Please provide more context around this exception.

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
