### ISSUE TITLE
HandleRedirect is not working properly

### ISSUE THREAD

**Issue by connect2satz** [google/google-http-java-client#397]
I am using com.google.http-client:google-http-client-android:1.23.0 for my development, My url request returns 302 response code, but my redirect request is failing with error code 404.

In my tcp dump I am seeing redirected request is using POST method instead of GET, but the same flow is working with apache http client.

**Comment by connect2satz** [comment]
http://httpcomponents.10934.n7.nabble.com/HttpClient-4-1-2-and-redirect-handling-td11882.html

Looks like my apache client(version 4.1) is handling 302 response automatically, it could be using predefined RedirectStrategy. 

Does google http-client has anything similar to this ? Currently I handled this response code manually.

**Comment by mattwhisenhunt** [comment]
Are you having trouble accessing a Google API?

**Comment by connect2satz** [comment]
Hi Matt,
     Is there any reason why that status code 302 is not handled ??

Thanks,
Sathish

**Comment by mattwhisenhunt** [comment]
I believe your implementation of HttpTransport is what controls redirect handling. So you can use the provided com.google.api.client.http.apache.ApacheHttpTransport and get the expected handling from Apache HttpClient library. You can also implement your own from scratch and use [ApacheHttpTransport](https://github.com/google/google-http-java-client/blob/dev/google-http-client/src/main/java/com/google/api/client/http/apache/ApacheHttpTransport.java) or [MockHttpTransport](https://github.com/google/google-http-java-client/blob/dev/google-http-client/src/main/java/com/google/api/client/testing/http/MockHttpTransport.java) as references.

**Comment by JustinBeckwith** [comment]
Greetings!  We haven't heard anything for a while on this issue.  If you're still running into problems... please do let us know!
