### ISSUE TITLE
Does Google HTTP client handle cookies?

### ISSUE THREAD

**Issue by sryze** [google/google-http-java-client#405]
I could not find any mention of cookies anywhere in the documentation.  Does it automatically send cookies from previous requests, like Apache's HTTP client for example, or the user should handle that manually?

Regardless of whether Google HTTP client handles cookies or not I think that should be mentioned explicitly somewhere in the docs.

**Comment by mattwhisenhunt** [comment]
There are no cookiejars nor policies, cookies just get treated like any plain headers entry.
You could do something like:
```Java
client = HTTP_TRANSPORT.createRequestFactory(
  new HttpRequestInitializer() {
    @Override
    public void initialize(HttpRequest request) {
      request.getHeaders().setCookie(cookieStr);
    }
});
```
but then, yes, you would still have to manually set cookieStr after recieving each response.

You can also use [ApacheHttpTransport](https://github.com/google/google-http-java-client/blob/dev/google-http-client/src/main/java/com/google/api/client/http/apache/ApacheHttpTransport.java) and friends to have access to Apache's HTTP client.

**Comment by sryze** [comment]
OK, thanks.
