### ISSUE TITLE
XML libraries alternatives

### ISSUE THREAD

**Issue by George02** [google/google-http-java-client#407]
"The JSON and XML libraries are also fully pluggable". What are the alternatives for parsing XML responses ? I found google-http-client-xml which uses MXParser pretty buggy. For example if my element text contains a large [!<CDATA[ -- large text -- ]]> the cdata is not fully returned.

Could you also post examples of how to use them ?

**Comment by mattwhisenhunt** [comment]
I don't have any examples of using XML or any other pluggable implementation. If you have a parsing library in mind, I am more than willing to help you implement [ObjectParser](https://github.com/google/google-http-java-client/blob/dev/google-http-client/src/main/java/com/google/api/client/util/ObjectParser.java) with that library.

My XML knowledge is pretty foggy, am I remembering correctly that there are subtleties parsing CDATA blocks; like you have to buffer the whole thing before you start parsing? Is that what MXP is tripping over?

**Comment by George02** [comment]
In a [stackoverflow](https://stackoverflow.com/questions/2784183/what-does-cdata-in-xml-mean) post, Sean Vieira explains that "CDATA stands for Character Data and it means that the data in between these strings includes data that could be interpreted as XML markup, but should not be."

So when it's about <![CDATA[ --text here-- ]]> blocks you just want to get the text inside it. What MPX does now is that it returns only a part of the text not the entire one. The problem is here:

`    public String getText()
    {
        if(eventType == START_DOCUMENT || eventType == END_DOCUMENT) {
            //throw new XmlPullParserException("no content available to read");
            //      if(roundtripSupported) {
            //          text = new String(buf, posStart, posEnd - posStart);
            //      } else {
            return null;
            //      }
        } else if(eventType == ENTITY_REF) {
            return text;
        }
        if(text == null) {
            if(!usePC || eventType == START_TAG || eventType == END_TAG) {
                text = new String(buf, posStart, posEnd - posStart);
            } else {
                text = new String(pc, pcStart, pcEnd - pcStart);
            }
        }
        return text;
    }`

The value of the posEnd variable is wrong. My text has more than 1000 characters and posEnd is 343.


Later edit: Oh. I think i got it. The eventType in the above code is 4 which stands for text. Shoudn't it be 5 ?

    /**
     * Character data was read and will is available by calling getText().
     * <p><strong>Please note:</strong> <a href="#next()">next()</a> will
     * accumulate multiple
     * events into one TEXT event, skipping IGNORABLE_WHITESPACE,
     * PROCESSING_INSTRUCTION and COMMENT events,
     * In contrast, <a href="#nextToken()">nextToken()</a> will stop reading
     * text when any other event is observed.
     * Also, when the state was reached by calling next(), the text value will
     * be normalized, whereas getText() will
     * return unnormalized content in the case of nextToken(). This allows
     * an exact roundtrip without chnanging line ends when examining low
     * level events, whereas for high level applications the text is
     * normalized apropriately.
     *
     * @see #next
     * @see #nextToken
     * @see #getText
     */
    int TEXT = 4;

    /**
     * A CDATA sections was just read;
     * this token is available only from calls to <a href="#nextToken()">nextToken()</a>.
     * A call to next() will accumulate various text events into a single event
     * of type TEXT. The text contained in the CDATA section is available
     * by callling getText().
     *
     * @see #nextToken
     * @see #getText
     */
    int CDSECT = 5;

**Comment by George02** [comment]
I didn't had time for that. I parsed it a as string and then I threw it in an XML parser implemented by myself.

**Comment by mattwhisenhunt** [comment]
Alright. Give us a holler if you need anything else.
