### ISSUE TITLE
Parent POM 1.24.1 missing from Maven Central

### ISSUE THREAD

**Issue by jeffclary** [google/google-http-java-client#438]
My Maven project is failing to resolve a dependency on com.google.http-client:google-http-client-appengine:jar:1.24.1 because it can't find the parent POM.  

Checking http://search.maven.org/#search%7Cga%7C1%7Cgoogle-http-client-parent the latest parent POM artifact is version 1.23.0.  I guess this was missed during the July 30 release?

**Comment by aschroder** [comment]
We're seeing this too with dependencies broken:

`Failed to collect dependencies at com.google.appengine.tools:appengine-gcs-client:jar:0.6 -> com.google.api-client:google-api-client-appengine:jar:1.24.1 -> com.google.oauth-client:google-oauth-client-appengine:jar:1.24.1 -> com.google.http-client:google-http-client-appengine:jar:1.24.1: Failed to read artifact descriptor for com.google.http-client:google-http-client-appengine:jar:1.24.1: Failure to find com.google.http-client:google-http-client-parent:pom:1.24.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]`

**Comment by ichigo92** [comment]
Also experiencing this issue.
The metadata has version [1.24.1](http://central.maven.org/maven2/com/google/http-client/google-http-client/maven-metadata.xml) but the maven repository only has up to [1.23.0](https://mvnrepository.com/artifact/com.google.http-client/google-http-client).

**Comment by hienle-hps** [comment]
@jadekler Looks like the release missed `google-http-client-parent`.

**Comment by ichigo92** [comment]
Found a workaround by excluding the jars and added transitive dependency for the time being
https://stackoverflow.com/questions/38537416/maven-build-error-in-jenkins-semi-time-sensitive/38537760

**Comment by jadekler** [comment]
We are working on a fix for this now.

**Comment by jadekler** [comment]
We have manually pushed a release of the missing 1.24.1 parent. I've tested locally and it seems to fix the issue. Please double check and let me know if the problem still persists. I'll close the issue for now, but if anyone notes this problem still occurring I am happy to re-open this.

https://repo1.maven.org/maven2/com/google/http-client/google-http-client-parent/1.24.1/
