### ISSUE TITLE
Failed to resolve: com.google.http-client:google-http-client-parent:1.24.1

### ISSUE THREAD

**Issue by devvikas** [google/google-http-java-client#439]
I have these lines in my app gradle file.

    endpointsServer project(path: ':backend', configuration: 'endpoints')
    implementation 'com.google.api-client:google-api-client:1.24.1'
    implementation 'com.google.api-client:google-api-client-android:1.22.0'

I keep getting the error: Failed to resolve: com.google.http-client:google-http-client-parent:1.24.1

**Comment by elharo** [comment]
Looks like com.google.http-client:google-http-client-parent:1.24.1 was not published to Maven Central at the same time the other artifacts were.

**Comment by elharo** [comment]
Also, in this specific case don't depend on 'com.google.api-client:google-api-client:1.24.1'. It's not ready yet.

**Comment by jadekler** [comment]
Hi - apologies for the problems. As @elharo mentioned, you can work around this for the moment by pinning to 1.23.0. We're yanking 1.24.1 (https://issues.sonatype.org/browse/OSSRH-41618) and will publish 1.24.2 ASAP.

**Comment by devvikas** [comment]
There is  a work around posted on this stackoverflow thread. https://stackoverflow.com/questions/51623523/android-plugin-for-gradle-3-0-0-could-not-find-com-google-http-clientgoogle-h/51631503#51631503

It works. I have tested myself.

**Comment by jadekler** [comment]
We have manually pushed a release of the missing 1.24.1 parent. I've tested locally and it seems to fix the issue. Please double check and let me know if the problem still persists. I'll close the issue for now, but if anyone notes this problem still occurring I am happy to re-open this.

**Comment by gebba** [comment]
Can confirm this fixed our builds! Thanks!
